name: Run Test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    container:
      image: "centos:7"  # 使用 centos:7 镜像
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up DNS
        run: |
          echo 'nameserver 8.8.8.8' > /etc/resolv.conf

      - name: Update and Install Dependencies
        run: |
          yum clean all
          yum makecache
          yum install -y curl sudo createrepo yum-utils

      - name: Set Script Permissions
        run: |
          chmod +x generate_yum_repo.sh install_dependency.sh

      - name: Debug Directory Contents
        run: |
          echo "容器内文件列表:"
          ls -l

      - name: Generate Yum Repo
        run: |
          ./generate_yum_repo.sh -f dependencies.txt

      - name: Get YUM_REPO_TAR Path
        run: |
          YUM_REPO_TAR=$(ls agent_yum_repo_*.tar.gz | head -n 1)
          echo "离线包路径: $YUM_REPO_TAR"
          if [ -z "$YUM_REPO_TAR" ] || [ ! -f "$YUM_REPO_TAR" ]; then
            echo '错误：未找到有效的离线包，请检查 generate_yum_repo.sh 的执行结果。'
            exit 1
          fi

      - name: Install Dependencies
        run: |
          ./install_dependency.sh -f $YUM_REPO_TAR
