name: SH Scripts Test

on: [push]

jobs:
  test-sh-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          # 卸载可能存在的冲突包
          sudo apt-get remove -y containerd
          sudo apt-get autoremove -y

          # 安装 Docker（官方脚本）
          curl -fsSL https://get.docker.com | sudo sh

      - name: Verify Docker Installation
        run: |
          docker --version
          docker run hello-world

      - name: Run in CentOS 7 Container
        env:
          DEPS_FILE: dependencies.txt
        run: |
          docker pull centos:7
          docker run --rm -v $(pwd):/workdir centos:7 /bin/bash -c "
            yum install -y curl sudo createrepo yum-utils &&
            curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo &&
            yum makecache &&
            bash /workdir/generate_yum_repo.sh -f $DEPS_FILE &&
            bash /workdir/check_revshell_offline.sh
          "
